website: 'https://shop.thinkspaceprojects.com/
text_message: 'Website change! https://shop.thinkspaceprojects.com/'
twilio_phone_number: '+17472479302'
recipient_phone_number: '+14155192029'
ping_frequency_seconds: 5 