website: 'https://space-invaders.com/spaceshop/product/99108775083900940'
text_message: 'Website change! https://space-invaders.com/spaceshop'
recipient_phone_number: '+14155192029'
ping_frequency_seconds: 5 