website: 'https://hypebeast.com/'
text_message: 'Website change! https://space-invaders.com/spaceshop'
twilio_phone_number: '+17472479302'
recipient_phone_number: '+14155192029'
ping_frequency_seconds: 5 